DROP TABLE IF EXISTS INVENTORY;

CREATE TABLE INVENTORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  subcategory_id int NOT NUll,
  qty int not null
);

DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
);

DROP TABLE IF EXISTS CATEGORY_RELATION;

CREATE TABLE CATEGORY_RELATION (
  category_id int not null,
  subcategory_id int not null,
);

DROP TABLE IF EXISTS SUBCATEGORY;

CREATE TABLE SUBCATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  parentcategory_id int not null,
);


