drop table inv_category if exists
drop table inventory if exists
create table inv_category (category_id bigint generated by default as identity, name varchar(255) not null, parent_category_id bigint, primary key (category_id))
create table inventory (inventory_id bigint generated by default as identity, name varchar(255) not null, qty bigint, category_id bigint, primary key (inventory_id))
alter table inventory add constraint FK_INV_CATEGORY foreign key (category_id) references inv_category